import { createFileRoute, Link } from "@tanstack/react-router";
import { useState } from "react";
import { Film, Tv, Lightbulb, ScanSearch } from "lucide-react";
import { PageHeader, SegBadge, segColor, btn } from "@/components/AppShell";
import { SEGMENTS, recommend, analyzeUser, DEMO_INPUT, type Analysis } from "@/lib/model";
import { useAnalysis } from "@/lib/store";

export const Route = createFileRoute("/recommendations")({
  head: () => ({
    meta: [
      { title: "Recommendations — AudienceIQ" },
      { name: "description", content: "Transparent, rule-based content recommendations per audience segment." },
      { property: "og:title", content: "Recommendations — AudienceIQ" },
      { property: "og:description", content: "Transparent, rule-based content recommendations per audience segment." },
    ],
  }),
  component: Recs,
});

const RULES = [
  "Action + Thriller · Long-form series · Similar content",
  "Short movies · Trending content · Easy-to-complete episodes",
  "Preferred genres · Related genres · New genre discovery",
  "Popular content · Easy-to-watch movies · Trending short content",
];

function Recs() {
  const { analysis } = useAnalysis();
  const [override, setOverride] = useState<number | null>(null);
  const segId = override ?? analysis?.segment.id ?? 0;
  const a: Analysis = override !== null || !analysis
    ? { ...(analysis ?? analyzeUser(DEMO_INPUT)), segment: SEGMENTS[segId]! }
    : analysis;
  const items = recommend(a);

  return (
    <>
      <PageHeader eyebrow="Personalization engine" title="Personalized Recommendations"
        desc="Every recommendation is generated by explicit segment rules — no black box, every suggestion explains itself." />

      <div className="panel mb-6 flex flex-col gap-4 p-5 md:flex-row md:items-center md:justify-between">
        <div>
          {analysis ? (
            <div className="text-sm">Recommendations for <span className="font-mono text-accent">{analysis.input.userId}</span> · {analysis.confidence}% confidence</div>
          ) : (
            <div className="flex items-center gap-2 text-sm text-muted-foreground">No user analyzed yet — previewing by segment. <Link to="/analyzer" className="inline-flex items-center gap-1 text-accent hover:underline"><ScanSearch className="h-3.5 w-3.5" />Analyze a user</Link></div>
          )}
          <div className="mt-2 flex items-center gap-2 text-xs text-muted-foreground"><Lightbulb className="h-3.5 w-3.5 text-warning" />Rule: {RULES[segId]}</div>
        </div>
        <div className="flex flex-wrap gap-2">
          {SEGMENTS.map((s) => (
            <button key={s.id} onClick={() => setOverride(s.id === analysis?.segment.id ? null : s.id)}
              className={`rounded-full transition ${segId === s.id ? "ring-2 ring-offset-2 ring-offset-background" : "opacity-60 hover:opacity-100"}`}
              style={{ ["--tw-ring-color" as string]: segColor(s.id) }}>
              <SegBadge id={s.id} name={s.short} />
            </button>
          ))}
        </div>
      </div>

      <div key={segId} className="grid gap-5 sm:grid-cols-2 xl:grid-cols-3">
        {items.map((t, i) => (
          <div key={t.title} className="panel panel-hover animate-in fade-in slide-in-from-bottom-2 overflow-hidden" style={{ animationDelay: `${i * 60}ms`, animationFillMode: "both" }}>
            <div className="relative h-36 overflow-hidden" style={{ background: `linear-gradient(135deg, color-mix(in oklab, ${segColor(segId)} 70%, var(--background)), var(--surface) 80%)` }}>
              <div className="absolute inset-0 opacity-30" style={{ backgroundImage: "repeating-linear-gradient(115deg, transparent 0 18px, var(--foreground) 18px 19px)" }} />
              <div className="absolute bottom-3 left-4 right-4">
                <div className="font-display text-xl font-bold drop-shadow">{t.title}</div>
              </div>
              <span className="absolute right-3 top-3 inline-flex items-center gap-1 rounded-md bg-background/70 px-2 py-0.5 text-[11px] backdrop-blur">
                {t.type === "Movie" ? <Film className="h-3 w-3" /> : <Tv className="h-3 w-3" />}{t.type}
              </span>
              <span className="absolute left-3 top-3 rounded-md bg-background/70 px-2 py-0.5 font-mono text-[11px] backdrop-blur">#{i + 1}</span>
            </div>
            <div className="p-4">
              <div className="text-sm text-muted-foreground">{t.genre} • {t.duration}</div>
              <p className="mt-3 rounded-lg border border-border bg-surface p-3 text-sm">
                <span className="text-accent">Why: </span>Recommended because {t.reason.charAt(0).toLowerCase() + t.reason.slice(1)}
              </p>
            </div>
          </div>
        ))}
      </div>
      {!analysis && <div className="mt-6 text-center"><Link to="/analyzer" className={btn.primary}>Analyze a user for personalized picks</Link></div>}
    </>
  );
}
